# Made by js6pak and modified by wyvest

name: Java CI

on: [ push, workflow_dispatch ]

jobs:
  build-natives:
    strategy:
      matrix:
        os: [macos-latest]
        arch: [arm64]
    runs-on: ${{ matrix.os }}
    continue-on-error: true
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 8
      uses: actions/setup-java@v4
      with:
        java-version: 8
        distribution: zulu
        architecture: ${{ matrix.arch }}
    - if: matrix.os == 'macos-latest'
      run: sudo xcode-select -s /Applications/Xcode_16.4.0.app/Contents/Developer
    - name: Build natives
      run: ant generate-all compile_native
    - uses: actions/upload-artifact@v4
      with:
        name: natives-${{ matrix.os }}-${{ matrix.arch }}
        path: |
          bin/lwjgl/lwjgl*.dll
          bin/lwjgl/liblwjgl*.so
          bin/lwjgl/liblwjgl.dylib

  build:
    runs-on: ubuntu-latest
    needs: build-natives
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up JDK 8
        uses: actions/setup-java@v4
        with:
          java-version: 8
          distribution: zulu
      - uses: actions/download-artifact@v4
        with:
          pattern: natives-*
          path: bin/lwjgl
          merge-multiple: true
      - name: Build
        run: ant generate-all maven-full
      - uses: actions/upload-artifact@v4
        with:
          name: maven
          path: dist/lwjgl-maven-*.zip
